[workspace]
resolver = "3"
members = ["lib", "cli"]

[workspace.metadata.crane]
name = "horizon"

[workspace.dependencies]
horizon-lib = { path = "lib" }

serde      = { version = "1", features = ["derive"] }
serde_json = "1"
protos = { git = "https://github.com/LiGoldragon/protos", rev = "1febca7836bf8d5f5973a302fdd50aa9c84c159b" }
datom-codec = { git = "https://github.com/LiGoldragon/datom-codec", rev = "09e2a9d52bf7f2f11e51d15cb6c3177f72c6c927", features = ["rkyv"] }
ethos-zero = { git = "https://github.com/LiGoldragon/ethos-zero", rev = "4bf73cae8d4f5a2072c76a11cd2f00aa3fe9f8e3" }
thiserror  = "2"
clap       = { version = "4", features = ["derive"] }
