[package]
name    = "horizon-cli"
version = "0.5.0"
edition = "2024"

[[bin]]
name = "horizon-cli"
path = "src/main.rs"

[dependencies]
horizon-lib = { workspace = true }
datomic = { workspace = true }
protos = { workspace = true }
serde_json  = { workspace = true }
clap        = { workspace = true }
