[package]
name    = "horizon-lib"
version = "0.7.0"
edition = "2024"
build = "build.rs"
autotests = false

[dependencies]
serde      = { workspace = true }
protos = { workspace = true }
datom-codec = { workspace = true }
thiserror  = { workspace = true }

[build-dependencies]
ethos-zero = { workspace = true }

[[test]]
name = "contract"
path = "tests/contract.rs"
