[package]
name    = "horizon-lib"
version = "0.6.0"
edition = "2024"
autotests = false

[dependencies]
serde      = { workspace = true }
protos = { workspace = true }
datom-codec = { workspace = true }
ethos-zero = { workspace = true }
thiserror  = { workspace = true }

[[test]]
name = "contract"
path = "tests/contract.rs"
