[package]
name    = "horizon-lib"
version = "0.5.1"
edition = "2024"

[dependencies]
serde      = { workspace = true }
protos = { workspace = true }
datomic = { workspace = true }
ethos-zero = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
thiserror  = { workspace = true }
ipnet      = { workspace = true }

[[bin]]
name = "horizon-regenerate"
path = "tools/regenerate.rs"
